# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Solving Linear Equations using Rcpp and Armadillo
#' @description Solves a linear system of equations by extracting certain columns from matrix X, then applying transformations and solving Ax = b.
#' @param X A matrix representing the coefficient matrix.
#' @param Alnew A vector of unsigned integers indicating the indices of columns of X to be used.
#' @param y A vector representing the right-hand side of the equation.
#' @return A vector that is the solution to the linear system.
#' @examples
#' # Assuming X is a matrix, Alnew is a vector of indices, and y is a vector
#' # solveEquation(X, Alnew, y) solves the system of equations and returns the solution
#' @export
solveEquation <- function(X, Alnew, y) {
    .Call('_SA23204173_solveEquation', PACKAGE = 'SA23204173', X, Alnew, y)
}

